version: "3.3"

networks:
  loki:
    driver: bridge

services:
#  loki:
#    image: grafana/loki:2.7.5
#    ports:
#    - 3100:3100
#    command:
#    - -config.file=/etc/loki/local-config.yaml
#    - -print-config-stderr=true
#    networks:
#    - loki
  
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
#    depends_on:
#    - loki
    volumes:
    - monitoring_grafana_data:/var/lib/grafana
    networks:
    - loki
    
  websocketserver:
    image: websocketserver
    ports:
    - 7070:7070
    networks:
    - loki
    
volumes:
   monitoring_grafana_data:
     external: true