global:
  scrape_interval:     5s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: metric_publish_app
    static_configs:
      - targets: ['127.0.0.1:8081']
#        labels:
#          instace_name: 'testing'